"""empty message

Revision ID: 021f5fbb6623
Revises: d950e4c1abf8
Create Date: 2022-05-16 09:41:58.833195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021f5fbb6623'
down_revision = 'd950e4c1abf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('createdAt', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'createdAt')
    # ### end Alembic commands ###
