"""empty message

Revision ID: d950e4c1abf8
Revises: 
Create Date: 2022-05-13 07:59:52.575770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd950e4c1abf8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('accountNumber', sa.Integer(), nullable=False),
    sa.Column('currencyCode', sa.Enum('TRY', 'USD', 'EUR', name='currencycodeenum'), nullable=True),
    sa.Column('ownerName', sa.String(length=128), nullable=True),
    sa.Column('accountType', sa.Enum('individual', 'corporate', name='accounttypeenum'), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('senderAccount', sa.Integer(), nullable=True),
    sa.Column('receiverAccount', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('transactionType', sa.Enum('payment', 'deposit', 'withdraw', name='transactionnameenum'), nullable=True),
    sa.PrimaryKeyConstraint('accountNumber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    # ### end Alembic commands ###
